# Generated by Django 2.0.5 on 2018-06-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True, verbose_name='Type')),
                ('message', models.CharField(max_length=64, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='SentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], default='F', max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.NotificationType')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20, verbose_name='Type')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('imei', models.CharField(max_length=20, unique=True, verbose_name='IMEI')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice')),
            ],
        ),
        migrations.AddField(
            model_name='subscribenotification',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Vehicle'),
        ),
        migrations.AddField(
            model_name='senthistory',
            name='notifyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.SubscribeNotification'),
        ),
        migrations.AddField(
            model_name='senthistory',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribenotification',
            unique_together={('vehicle', 'notifyType')},
        ),
    ]
