# Generated by Django 2.0.5 on 2018-06-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180609_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='senthistory',
            name='vehicle_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Vehicle Address'),
        ),
    ]
